version: "3.8"
services:
  nadia_web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./Code:/Code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - nadia_php
  nadia_php:
    image: php:8.3-fpm